name: UniSoccer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.18
  - av==11.0.0
  - decord==0.6.0
  - einops==0.8.0
  - imageio==2.34.2
  - numpy==1.24.4
  - opencv-python==4.10.0.84
  - peft==0.13.2
  - Pillow==11.1.0
  - pycocoevalcap==1.2
  - requests==2.32.3
  - sentence-transformers==3.0.1
  - timm==1.0.12
  - pytorch==2.3.1
  - torchvision==0.18.1
  - tqdm==4.66.4
  - transformers==4.43.2
  - wandb==0.19.1
  - pip:
      - torch==2.3.1
